// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbfcGy9UPcgu3TzbUwIsZiGmABnD-bClM',
    appId: '1:1086690705290:web:0f007ff83fdcd0c5251273',
    messagingSenderId: '1086690705290',
    projectId: 'big-lore-386620',
    authDomain: 'big-lore-386620.firebaseapp.com',
    storageBucket: 'big-lore-386620.appspot.com',
    measurementId: 'G-DM6HLBPS9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-EYMRS5uWR5frex63vUCsfZWbiXfFtXU',
    appId: '1:1086690705290:android:a8b553f10f9e5088251273',
    messagingSenderId: '1086690705290',
    projectId: 'big-lore-386620',
    storageBucket: 'big-lore-386620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayNMEC-kTHm8tK90soGeKQHDoSCp2Sn4',
    appId: '1:1086690705290:ios:fe160f5e1acae24f251273',
    messagingSenderId: '1086690705290',
    projectId: 'big-lore-386620',
    storageBucket: 'big-lore-386620.appspot.com',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCayNMEC-kTHm8tK90soGeKQHDoSCp2Sn4',
    appId: '1:1086690705290:ios:ed2da3bc103550fe251273',
    messagingSenderId: '1086690705290',
    projectId: 'big-lore-386620',
    storageBucket: 'big-lore-386620.appspot.com',
    iosBundleId: 'com.example.university.RunnerTests',
  );
}
