// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB97xkwhJVYV9puHwURCdzO8LrpDw7EwA',
    appId: '1:955168211941:web:9df9a1ec73604b61b2e50c',
    messagingSenderId: '955168211941',
    projectId: 'universty-app-shabaan',
    authDomain: 'universty-app-shabaan.firebaseapp.com',
    storageBucket: 'universty-app-shabaan.appspot.com',
    measurementId: 'G-RPSQ700RK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwzGdw0jjPQ84yw0weMjhhr8AGK7Jc-A',
    appId: '1:955168211941:android:fd98743c8ad2eeb7b2e50c',
    messagingSenderId: '955168211941',
    projectId: 'universty-app-shabaan',
    storageBucket: 'universty-app-shabaan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89pPnNZjjJLk83hoA9OwMKeL-Cb4VhYw',
    appId: '1:955168211941:ios:5ac7974506e04891b2e50c',
    messagingSenderId: '955168211941',
    projectId: 'universty-app-shabaan',
    storageBucket: 'universty-app-shabaan.appspot.com',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA89pPnNZjjJLk83hoA9OwMKeL-Cb4VhYw',
    appId: '1:955168211941:ios:64e38ca34ef333a9b2e50c',
    messagingSenderId: '955168211941',
    projectId: 'universty-app-shabaan',
    storageBucket: 'universty-app-shabaan.appspot.com',
    iosBundleId: 'com.example.university.RunnerTests',
  );
}
